# Generated by Django 3.2.5 on 2021-07-20 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('goal', models.CharField(blank=True, max_length=80)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='month_app.client')),
            ],
            options={
                'verbose_name': 'event',
                'ordering': ['date', 'client'],
                'get_latest_by': 'date',
            },
        ),
    ]
