<<<<<<< HEAD
# Generated by Django 3.2.5 on 2021-07-15 16:04

from django.db import migrations, models
=======
# Generated by Django 3.2.5 on 2021-07-12 15:52

from django.db import migrations, models
import django.db.models.deletion
>>>>>>> 540943b1c1b5614d2936b24239865a96261e9922


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
=======
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='month_app.client')),
            ],
            options={
                'verbose_name': 'event',
                'ordering': ['date', 'client'],
                'get_latest_by': 'date',
            },
        ),
>>>>>>> 540943b1c1b5614d2936b24239865a96261e9922
    ]
