# Generated by Django 3.2.5 on 2021-07-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('month_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='goal',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
