# Generated by Django 3.2.5 on 2021-07-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal_app', '0002_alter_myuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='when',
            field=models.DateField(),
        ),
    ]
